services:
  - type: web
    name: banana-flask-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flutter:app  # Correct the app name
    envVars:
      - key: FLASK_ENV
        value: production
